apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/vote

images:
  - name: vote-image
    newName: devacr.azurecr.io/vote
    newTag: dev-1.0.0

patches:
  - path: ./patches/deployment.yaml
    target:
      kind: Deployment
      name: vote

  - path: ./patches/hpa.yaml
    target:
      kind: HorizontalPodAutoscaler
      name: vote
