---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: runtime-staging
  namespace: flux-system
spec:
  dependsOn:
    - name: vcluster-staging
  interval: 5m
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: gitops-k8s-config
  path: ./clusters/aks/env/staging
