---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote
  namespace: app-vote
  labels:
    app: vote
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
        - name: vote
          # Placeholder for image, to be replaced in overlays
          image: vote-image
          ports:
            - name: http
              containerPort: 80
