---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vcluster-prod
  namespace: vcluster-prod
spec:
  interval: 5m
  chart:
    spec:
      chart: vcluster
      version: "0.19.x"
      sourceRef:
        kind: HelmRepository
        name: vcluster
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: vcluster-values
      valuesKey: values.yaml
