apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # 1) shared：shared resources（namespaces/sources）
  - ../../shared/sources
  - ../../shared/namespaces
  # 2) vcluster: environment overlay
  - ../../vclusters/staging
  # 3) platform: environment overlay (ingress/cert-manager/monitoring)
  #- ../../../../platform/overlays/staging
  # 4) apps：environment overlay
  #- ../../../../apps/overlays/staging
