---
apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: gitops-k8s-config
  namespace: flux-system
spec:
  interval: es
  url: https://github.com/qianyang81/gitops-k8s-config.git
  ref:
    branch: main
