apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  # platform: environment overlay (ingress/cert-manager/monitoring)
  #- ../../../../platform/overlays/prod
  # apps：environment overlay
  - ../../../../apps/overlays/prod
